KEYS = {
    'High G': [],
    'F#': [],
    'F': [],
    'E': [],
    'Eb': [],
    'D': [],
    'Db': [],
    'C': [],
    'B(H)': [],
    'Bb': [],
    'A': [],
    'Ab': [],
    'G': [],
    'Low F': [],
    'Low E': [],
    'Low Eb': [],
    'Low D': [],
    'Low C': [],
    'Low Bb': [],
    'Low A': [],
    'Low G': [],
    'Low-Low F': [],
}