KEYS = {
    'High G': [7],
    'F#': 6,
    'F': 5,
    'E': 4,
    'Eb': 3,
    'D': 2,
    'Db': 1,
    'C': 0,
    'B(H)': -1,
    'Bb': -2,
    'A': -3,
    'Ab': -4,
    'G': -5,
    'Low F': -7,
    'Low E': -8,
    'Low Eb': -9,
    'Low D': -10,
    'Low C': -12,
    'Low Bb': -14,
    'Low A': -15,
    'Low G': -17,
    'Low-Low F': -19,
}

# C - 48 - 60